spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: roadmap
            auto-index-creation: true
logging:
    level:
        org.springframework.data.mongodb: DEBUG
